feature_extract_enable : 0
point_filter_num : 2
max_iteration : 5
dense_map_enable : 1
filter_size_surf : 0.15
filter_size_map : 0.25
cube_side_length : 100
grid_size : 40
patch_size : 8
img_enable : 1
lidar_enable : 1
outlier_threshold : 156 # 78 100 156
ncc_en: false
ncc_thre: 0
img_point_cov : 100000 # 1000
laser_point_cov : 0.001 # 0.001
pose_output_en: false
delta_time: 0.0

common:
    lid_topic:  "/lidar_points"
    imu_topic:  "/IMU_data"

preprocess:
    lidar_type: 4 # 1:Livox LiDAR  2:VELO16  3:OUST64  4:XT32  5:Mid360
    scan_line: 120 # 16  64  32
    blind: 1.5 # blind x m disable

mapping:
    acc_cov_scale: 100
    gyr_cov_scale: 100
    extrinsic_T: [0.157, 0.054, 0.01] # truth 
    extrinsic_R: [0.93066402, -0.00312472,  0.36586161,
                -0.00682122, -0.99993791,  0.00881136,
                0.36581136, -0.01069604, -0.93062755]

pcd_save:
    pcd_save_en: true

# 外参矩阵 ft120 to 57
camera:
    img_topic: /cam_raw_data0/compressed
    Rcl: [0.00241298,    0.999457,   0.0328768,
         -0.0486264,  -0.0327207,    0.998281,
          0.998814, -0.00400752,    0.048521]  
    Pcl: [ -0.174106,  0.0325364, 0.00823873]
    
